[package]
name = "terbium"
authors = ["jay3332", "Cryptex"]
version = "0.0.1"
edition = "2021"

[workspace]
members = ["terbium_grammar"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terbium_grammar = { version = "0.1", path = "terbium_grammar" }

[profile.dev]
opt-level = 2
