name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Test terbium
      run: cargo test --verbose

    - name: Test terbium_grammar
      run: cargo test -p terbium_grammar --verbose

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-build
        path: target/debug/terbium.exe

    - name: Upload Linux / MacOS Artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os != 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-build
        path: target/debug/terbium

    - name: Build release build
      run: cargo build --release --verbose

    - name: Upload Windows release artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-release-build
        path: target/release/terbium.exe

    - name: Upload Linux / MacOS release Artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os != 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-release-build
        path: target/release/terbium      
