name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: ubuntu-latest
            cmd: sudo apt-get update ; sudo apt install gcc-multilib
            target: i686-unknown-linux-gnu

          - os: macos-latest
            target: x86_64-apple-darwin
          
          - os: macos-latest
            target: aarch64-apple-ios

          - os: macos-latest
            target: aarch64-apple-darwin
          
          - os: windows-latest
            target: x86_64-pc-windows-gnu

          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - run: ${{ matrix.cmd }}

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        override: true

    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose

    - name: Test terbium
      run: cargo test --target ${{ matrix.target }} --verbose

    - name: Test terbium_grammar
      run: cargo test --target ${{ matrix.target }} -p terbium_grammar --verbose

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-build
        path: target/debug/terbium.exe

    - name: Upload Linux / MacOS / IOS  Artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os != 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-build
        path: target/debug/terbium

    - name: Build release build
      run: cargo build --release --verbose

    - name: Upload Windows release artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-release-build
        path: target/release/terbium.exe

    - name: Upload Linux / MacOS / IOS release Artifact
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os != 'windows-latest'}}
      with:
        name: ${{ matrix.os }}-release-build
        path: target/release/terbium      
